### ISSUE TITLE
[Unity/Android] Build error. Some library cannot load by gradle

### ISSUE THREAD

**Issue by itshipvn** [Particle-Network/particle-unity#1]
Hello,
I implement  ParticleAuthService to my project. But when i build project to apk. This error occur.
Please help to check.

Configuration:
   Unity 2022.3.12f1
   
![image](https://github.com/Particle-Network/particle-unity/assets/50375397/dd399598-e092-40e4-90eb-e172a8836a30)

Error log: 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':launcher:debugCompileClasspath'.
   > Could not find com.github.WalletConnect.Scarlet:lifecycle-android:1.0.0.
     Required by:
         project :launcher > com.walletconnect:android-core:1.24.0
   > Could not find com.github.komputing.kethereum:bip39:0.85.7.
     Required by:
         project :launcher > com.walletconnect:android-core:1.24.0
   > Could not find com.github.komputing.kethereum:bip39_wordlist_en:0.85.7.
     Required by:
         project :launcher > com.walletconnect:android-core:1.24.0
   > Could not find com.github.komputing.kethereum:bip32:0.85.7.
     Required by:
         project :launcher > com.walletconnect:android-core:1.24.0
   > Could not find com.github.komputing.kethereum:model:0.85.7.
     Required by:
         project :launcher > com.walletconnect:android-core:1.24.0
   > Could not find com.github.komputing.kethereum:crypto_impl_spongycastle:0.85.7.
     Required by:
         project :launcher > com.walletconnect:android-core:1.24.0
   > Could not find com.github.WalletConnect.Scarlet:scarlet:1.0.0.
     Required by:
         project :launcher > com.walletconnect:foundation:1.12.0
   > Could not find com.github.WalletConnect.Scarlet:websocket-okhttp:1.0.0.
     Required by:
         project :launcher > com.walletconnect:foundation:1.12.0
   > Could not find com.github.WalletConnect.Scarlet:stream-adapter-coroutines:1.0.0.
     Required by:
         project :launcher > com.walletconnect:foundation:1.12.0
   > Could not find com.github.WalletConnect.Scarlet:message-adapter-moshi:1.0.0.
     Required by:
         project :launcher > com.walletconnect:foundation:1.12.0
   > Could not find com.github.multiformats:java-multibase:1.1.1.
     Required by:
         project :launcher > com.walletconnect:foundation:1.12.0

**Comment by xxhong** [comment]
reference https://github.com/Particle-Network/particle-unity/tree/main/Assets/Plugins/Android

**Comment by itshipvn** [comment]
> reference https://github.com/Particle-Network/particle-unity/tree/main/Assets/Plugins/Android

Yes, I setup it exactly like that
![image](https://github.com/Particle-Network/particle-unity/assets/50375397/4c403841-842b-4b4a-9f20-c5664828d4d9)
