### ISSUE TITLE
[Unity/Android]Build apk Error

### ISSUE THREAD

**Issue by dengswing** [Particle-Network/particle-unity#2]
Hello,
I use [Particle Unity SDK 1.3.4]  project. export apk error.
Please help to check.

Configuration:
Unity 2022.3.17f1

> Configure project :
Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven2' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven3' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'maven4' was added by build file 'build.gradle'
Build was configured to prefer settings repositories over project repositories but repository 'flatDir' was added by build file 'build.gradle'

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Unity\particle-unity-release-1.3.4\Library\Bee\Android\Prj\Mono2x\Gradle\launcher\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':launcher'.
> Failed to apply plugin 'com.android.internal.version-check'.
   > Cannot parse project property android.enableR8='' of type 'class java.lang.String' as boolean. Expected 'true' or 'false'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 640ms

**Comment by xxhong** [comment]
Put all error messages from Android Studio into a txt file
