### ISSUE TITLE
connect OKX wallet Error

### ISSUE THREAD

**Issue by dengswing** [Particle-Network/particle-unity#3]
Hi，
connect OKX wallet Error

 I am using sdk Version 1.4.13

Please help to check.

`AndroidJavaException: java.lang.NullPointerException

java.lang.NullPointerException
network.particle.unity.module.ConnectBridge.connect(ConnectBridge.kt:149)
network.particle.unity.UnityBridgeConnect.connect(UnityBridgeConnect.kt:80)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loopOnce(Looper.java:201)
android.os.Looper.loop(Looper.java:288)
com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._CallStatic (System.IntPtr methodID, System.Object[] args) (at <00000000000000000000000000000000>:0)
Network.Particle.Scripts.Core.ParticleConnectInteraction.Connect (Network.Particle.Scripts.Model.WalletType walletType, Network.Particle.Scripts.Model.ConnectConfig config) (at <00000000000000000000000000000000>:0)
Network.Particle.Scripts.Core.ParticleConnect.Connect (Network.Particle.Scripts.Model.WalletType walletType, Network.Particle.Scripts.Model.ConnectConfig config) (at <00000000000000000000000000000000>:0)
SdkManager.Connect (Network.Particle.Scripts.Model.WalletType walletType) (at <00000000000000000000000000000000>:0)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <00000000000000000000000000000000>:0)
SdkManager.Connect (Network.Particle.Scripts.Model.WalletType walletType) (at <00000000000000000000000000000000>:0)
SdkManager.ChainChoiceAction (Network.Particle.Scripts.Model.ChainInfo chainInfo, Network.Particle.Scripts.Model.WalletType walletType) (at <00000000000000000000000000000000>:0)
SdkManager.WalletChoiceAction (Network.Particle.Scripts.Model.WalletType walletType) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (UnityEngine.EventSystems.PointerEventData pointerEvent, System.Boolean pressed, System.Boolean released) (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchEvents () (at <00000000000000000000000000000000>:0)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at <00000000000000000000000000000000>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <00000000000000000000000000000000>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <00000000000000000000000000000000>:0)`

**Comment by xxhong** [comment]
https://github.com/Particle-Network/particle-unity/blob/main/Assets/Plugins/Android/launcherTemplate.gradle
change sdkVersion to 1.4.19

**Comment by dengswing** [comment]
thanks
